### ISSUE TITLE
Loading/timeout classes for rules

### ISSUE THREAD

**Issue by averyhadzi** [trebor/coral#3]
I'm hoping to hook onto a class ('loading') that's only on the rule while it's loading, so I can show the spinner icon instead of the remove icon. 

Additionally, adding a class when tweets can't be found ('timeout') would be helpful - we could then show the "not enough tweets" state/message.

**Comment by trebor** [comment]
yes!  i'll plug this in as soon as i have the new rule system up and running.

**Comment by trebor** [comment]
we now have:

      <span class="seed-candidate"></span>
      <span class="message-text"></span>

the 'seed-candidate' span may also have 'requested', 'accepted' or 'rejected' classes appended accordingly.  the logic for that is here:

  https://github.com/trebor/coral/blob/master/public/src/control.js#L52

sorry about the d3 instead of the jquery, it is my native dom tool. :)

how's that look?

**Comment by trebor** [comment]
i think we got this covered.
